application: browserstatsall
version: test
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static/

libraries:
- name: webapp2
  version: "2.5.1"
